spring:
  application:
    name: post-product-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 192.168.1.21
    port: 5672
    username: myuser
    password: secret