spring:
  application:
    name: post-product-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:myuser}
    password: ${RABBITMQ_PASSWORD:secret}

rabbitmq:
  request:
    exchange: product-request
  response:
    exchange: product-response
    queue:
      name: product-response
server:
  port: 8081